version: '2'
services:
  db:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    depends_on:
      - db
